### ISSUE TITLE
iobroker.harmony stopped working

### ISSUE THREAD

**Issue by Lumumba76** [iobroker-community-adapters/ioBroker.harmony#102]
Since a few days the adapter wont recognize my hubs.
By default i set it to Auto Discover.
I also tried adding Addresses manually - same result.
The Adapter connects only to one of my three hubs.

Debian 11 / LXC-Container
admin v6.12.0
Node.js v16.20.2
NPM: 8.19.4
Harmony v1.3.0

**Comment by mcm1957** [comment]
I suggest to open a Topic at forum. This might lead to a fester solution if the problem is not caused by some codeing error.

**Comment by mcm1957** [comment]
Please retry with 1.5.0 which allows multiple subnets. See README.

**Comment by mcm1957** [comment]
no more feedback - so lets assume all is fine
