### ISSUE TITLE
Adapter does nothing

### ISSUE THREAD

**Issue by Karkas66** [iobroker-community-adapters/ioBroker.harmony#124]
I have my harmony running in a separate Wlan Sub Network. Iobroker runs on x64 hardware on Ethernet Sub Network.

After the adapter Installation nothing happens, the objects in the tree are not even created, just the folder harmony and harmony.admin

Is it maybe due to the fact that i´m already on Node.js v18.17.1 ?

**Comment by mcm1957** [comment]
First of all add RELEASE VERSIONS to all bug isszes.

Adapter
Js-controller
Node
O/S


Maybe you must specify subnet parameter. Copied the text from library example.

  // Example: Hub is within subnet 192.168.1.0/24, use address "192.168.1.255".
 
Node 18 iscrecommended nodecrelease. So this should be ok.

Note that I do not know the adapter in detail and do not own a device. So maybe it would be good to adk your question at forom.(https://forum.iobroker.net) as users there might know how to use at multiple network segnents.

**Comment by Karkas66** [comment]
Logitech Harmony Hub Version 4.15.330
Harmony Adapter v1.3.0
JS-Controller v7.1.6
OS Ubuntu 22.04.3 LTS

Added 10.10.10.255 in Subnet Configuration but Nothing changed

**Comment by mcm1957** [comment]
Adapter scans for hubs using UDB broadcat pacakges. So those pacaktes must be allowed to pass to the other subnet. Please ensure that no firewall / router is blocking them.

Eventually this topic might help too
https://forum.iobroker.net/topic/45086/gel%C3%B6st-harmony-adapter-legt-keine-objekte-an/2

**Comment by mcm1957** [comment]
please retra with 1.5.0 which will allow to specify multiple subnets now. See README.

**Comment by mcm1957** [comment]
no more feedback - so lets assume everything is fine
