### ISSUE TITLE
HarmonyHub in seperaten VLAN?

### ISSUE THREAD

**Issue by dfoxg** [iobroker-community-adapters/ioBroker.harmony#147]
Hallo,

ich würde gerne den Adapter weiterhin verwenden, allerdings findet der Adapter meinen Harmony nicht mehr sobald ich ihn in ein anderes VLAN/Subnetz geschoben habe. Auch die Angabe der IP in der Config funktioniert leider nicht (laut SourceCode ist das eher eine Allowlist als eine explizite Angabe)

**Comment by mcm1957** [comment]
I do not know the adapter. But a check of the source indoicates that hamony is searching the hub using broadcast UDP (IPv4) packets. Do you have your network configured to forward such pacaktes into the other vlan?

In addtion the following topic at forum might help
https://forum.iobroker.net/topic/45086/gel%C3%B6st-harmony-adapter-legt-keine-objekte-an/2

**Comment by dfoxg** [comment]
Hi  @mcm1957, thanks for linking that issue. 
Yeah i have a lot of problems with broadcast/multicast at the moment (spotify connect, ..), but the answer from `tugsi`  helped me, since i´m now pinned my harmonyhub-ip in the `Discovery subnet`, which works for me.

Thanks!
