### ISSUE TITLE
No Objects listed

### ISSUE THREAD

**Issue by Dietmar1963** [iobroker-community-adapters/ioBroker.harmony#64]
Hi - I installed iobroker (and other tools like deconz, influxdb, mosquitto, node-red, ...) on Raspberry 
in Docker containers. 
Within Iobroker I iadded adapters like fritzdect, deconz, bshb, dwd, tr-064, text2command, scripts.js . They all are running fine, objects are listed.
But after I installed the harmony adapter I see the system.adapter.harmony.0 instance with current data,  but  the harmony.0 objects folder is not created and not objects listed.
What could be the issue?
Thanks 
Best
Dietmar

Additional Info:
XMPP was activated in the app.

### system.adapter.harmony.0
![image](https://user-images.githubusercontent.com/56964291/76450919-e2efca80-63ce-11ea-9beb-d22842da5985.png)

### Log
harmony.0	2020-03-11 19:32:18.643	debug	(3310) system.adapter.admin.0: logging true
harmony.0	2020-03-11 19:32:18.643	silly	(3310) States system redis pmessage *.logging/system.adapter.admin.0.logging:{"val":true,"ack":true,"ts":1583951538633,"q":0,"from":"system.adapter.admin.0","lc":1583951538633}
harmony.0	2020-03-11 19:17:25.053	debug	(3310) system.adapter.admin.0: logging false
harmony.0	2020-03-11 19:17:25.052	silly	(3310) States system redis pmessage *.logging/system.adapter.admin.0.logging:{"val":false,"ack":true,"ts":1583950645042,"q":0,"from":"system.adapter.admin.0","lc":1583950645042}
harmony.0	2020-03-11 18:53:34.928	silly	(3310) States system redis pmessage system.adapter.harmony.0.sigKill/system.adapter.harmony.0.sigKill:null
harmony.0	2020-03-11 18:53:28.750	debug	(3310) system.adapter.admin.0: logging true
harmony.0	2020-03-11 18:53:28.748	silly	(3310) States system redis pmessage *.logging/system.adapter.admin.0.logging:{"val":true,"ack":true,"ts":1583949208720,"q":0,"from":"system.adapter.admin.0","lc":1583949208720}
harmony.0	2020-03-11 18:53:26.638	debug	(3310) system.adapter.admin.0: logging false
harmony.0	2020-03-11 18:53:26.636	silly	(3310) States system redis pmessage *.logging/system.adapter.admin.0.logging:{"val":false,"ack":true,"ts":1583949206620,"q":0,"from":"system.adapter.admin.0","lc":1583949206620}
harmony.0	2020-03-11 18:50:41.671	debug	(3310) system.adapter.admin.0: logging true
harmony.0	2020-03-11 18:50:41.670	silly	(3310) States system redis pmessage *.logging/system.adapter.admin.0.logging:{"val":true,"ack":true,"ts":1583949041661,"q":0,"from":"system.adapter.admin.0","lc":1583949041661}
harmony.0	2020-03-11 18:50:37.178	silly	(3310) States system redis pmessage system.adapter.harmony.0.logLevel/system.adapter.harmony.0.logLevel:{"val":"silly","ack":true,"ts":1583949037154,"q":0,"from":"system.adapter.harmony.0","lc":15839
harmony.0	2020-03-11 18:50:37.150	info	(3310) [DISCOVER] Searching for Harmony Hubs on 255.255.255.255
harmony.0	2020-03-11 18:50:37.113	debug	(3310) [START] Subnet: 255.255.255.255, Discovery interval: 10000
harmony.0	2020-03-11 18:50:37.081	info	(3310) starting. Version 1.2.2 in /opt/iobroker/node_modules/iobroker.harmony, node: v10.19.0

**Comment by tugsi** [comment]
Same Issue here.
No Objects like harmony.0.xxx 
But system.harmony.0.xx is listed.

**Comment by Khaos66** [comment]
I had the same issue and after adding TCP port 61991 to my docker container setup it worked fine ;)

**Comment by mcm1957** [comment]
As this issue is ruther old, I will close here.
Please open a new issue if problem still exists and add all relevant release informations:
- adapter
- js-controller
- admin
- node
- o/s
