### ISSUE TITLE
Adapter not Working

### ISSUE THREAD

**Issue by Snatch2001** [iobroker-community-adapters/ioBroker.harmony#65]
harmony.0 | 2020-05-24 07:32:21.180 | error | at TCP.onStreamRead (internal/stream_base_commons.js:94:17)
-- | -- | -- | --
harmony.0 | 2020-05-24 07:32:21.180 | error | at Socket.Readable.push (_stream_readable.js:224:10)
harmony.0 | 2020-05-24 07:32:21.180 | error | at readableAddChunk (_stream_readable.js:269:11)
harmony.0 | 2020-05-24 07:32:21.180 | error | at addChunk (_stream_readable.js:288:12)
harmony.0 | 2020-05-24 07:32:21.180 | error | at Socket.emit (events.js:198:13)
harmony.0 | 2020-05-24 07:32:21.180 | error | at Socket.socketOnData (_http_client.js:451:20)
harmony.0 | 2020-05-24 07:32:21.180 | error | at HTTPParser.parserOnHeadersComplete (_http_common.js:111:17)
harmony.0 | 2020-05-24 07:32:21.180 | error | at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)
harmony.0 | 2020-05-24 07:32:21.180 | error | at ClientRequest.emit (events.js:198:13)
harmony.0 | 2020-05-24 07:32:21.180 | error | at ClientRequest.req.on (/opt/iobroker/node_modules/harmonyhubws/node_modules/ws/lib/websocket.js:595:7)
harmony.0 | 2020-05-24 07:32:21.180 | error | (26152) Error: Unexpected server response: 401
harmony.0 | 2020-05-24 07:32:21.179 | error | (26152) uncaught exception: Unexpected server response: 401

**Comment by darkman242** [comment]
same here?!

harmony.0 | 2020-05-24 13:55:37.408 | error | (21241) Error: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
-- | -- | -- | --
harmony.0 | 2020-05-24 13:55:37.408 | error | (21241) uncaught exception: read ECONNRESET
harmony.0 | 2020-05-24 10:24:56.185 | error | at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
harmony.0 | 2020-05-24 10:24:56.185 | error | (17647) Error: read ECONNRESET
harmony.0 | 2020-05-24 10:24:56.185 | error | (17647) uncaught exception: read ECONNRESET

iobroker 3.1.4, nodejs 12.16.3, npm 6.14.4, Debian 10 (VM) unter Proxmox

**Comment by mcm1957** [comment]
As this issue is ruther old, I will close here.
Please open a new issue if problem still exists and add all relevant release informations:
- adapter
- js-controller
- admin
- node
- o/s
