### ISSUE TITLE
warn meldung

### ISSUE THREAD

**Issue by denjo1982** [iobroker-community-adapters/ioBroker.harmony#77]
ich habe immer folgende meldug wenn ich über meine fernbedienung mein hub steuere und nicht über iobroker.

`[SETSTATE] Unknown activityId: 51170190`

**Comment by mcm1957** [comment]
Please add all relevant release informations:
- adapter
- js-controller
- admin
- node
- o/s

**Comment by mcm1957** [comment]
closing as no response
